// Green Lake — catálogo inicial de obligaciones fiscales (borrador para revisión).
// Se carga una sola vez desde catalogo.html ("Cargar catálogo inicial") y a partir
// de ahí vive en la base de datos, donde se puede editar/ampliar libremente. Volver
// a pulsar "Cargar catálogo inicial" actualiza las entradas existentes (mismo código)
// con estos datos — revisa después si habías hecho cambios manuales.
//
// Plazos: calculados según la norma general de la AEAT (ver admin/deadlines.js).
// domiciliacion_offset_days = null significa "no domiciliable, solo NRC/informativo".
// Los modelos con periodicidad "puntual" (dependen de un hecho concreto: una venta,
// un alta, una herencia...) no generan fechas automáticas en el calendario.

const OBLIGATIONS_SEED = [
  // ---- IRPF / autónomos (persona física residente) ----
  { code: "modelo_100", name: "Modelo 100 — IRPF (Declaración de la Renta)", category: "IRPF", periodicity: "anual",
    description: "Declaración anual del Impuesto sobre la Renta de las Personas Físicas.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: false, juridica_no_residente: false,
    deadline_start_month: 4, deadline_start_day: 2, deadline_end_month: 6, deadline_end_day: 30, domiciliacion_offset_days: 5 },
  { code: "modelo_130", name: "Modelo 130 — Pago fraccionado IRPF (estimación directa)", category: "IRPF", periodicity: "trimestral",
    description: "Pago a cuenta trimestral del IRPF para autónomos en estimación directa.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: false, juridica_no_residente: false,
    quarterly_q4_extended: true, domiciliacion_offset_days: 5 },
  { code: "modelo_131", name: "Modelo 131 — Pago fraccionado IRPF (módulos)", category: "IRPF", periodicity: "trimestral",
    description: "Pago a cuenta trimestral del IRPF para autónomos en estimación objetiva (módulos).",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: false, juridica_no_residente: false,
    quarterly_q4_extended: true, domiciliacion_offset_days: 5 },
  { code: "modelo_714", name: "Modelo 714 — Impuesto sobre el Patrimonio", category: "Patrimonio", periodicity: "anual",
    description: "Declaración anual sobre el patrimonio neto, si supera el mínimo exento autonómico.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: false, juridica_no_residente: false,
    deadline_start_month: 4, deadline_start_day: 2, deadline_end_month: 6, deadline_end_day: 30, domiciliacion_offset_days: 5 },

  // ---- Ley Beckham (régimen especial de impatriados) ----
  { code: "modelo_149", name: "Modelo 149 — Solicitud del régimen de impatriados (Ley Beckham)", category: "Beckham", periodicity: "puntual",
    description: "Solicitud del régimen especial ante la Agencia Tributaria, dentro de los 6 meses desde el inicio de la relación laboral en España. Trámite único, no recurrente.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: false, juridica_no_residente: false },
  { code: "modelo_151", name: "Modelo 151 — IRPF de trabajadores desplazados (Ley Beckham)", category: "Beckham", periodicity: "anual",
    description: "Declaración anual del IRPF para quienes tributan bajo el régimen especial de impatriados (tipo fijo 24%/47%), una vez concedido el modelo 149. Sustituye al modelo 100 durante los años de aplicación del régimen.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: false, juridica_no_residente: false,
    deadline_start_month: 4, deadline_start_day: 2, deadline_end_month: 6, deadline_end_day: 30, domiciliacion_offset_days: 5 },

  // ---- IVA ----
  { code: "modelo_303", name: "Modelo 303 — IVA (autoliquidación trimestral)", category: "IVA", periodicity: "trimestral",
    description: "Declaración-liquidación trimestral del IVA repercutido y soportado.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    quarterly_q4_extended: true, domiciliacion_offset_days: 5 },
  { code: "modelo_390", name: "Modelo 390 — IVA (resumen anual)", category: "IVA", periodicity: "anual",
    description: "Resumen anual de las declaraciones trimestrales de IVA del ejercicio. Es informativo, sin cuota a domiciliar.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    deadline_start_month: 1, deadline_start_day: 1, deadline_end_month: 1, deadline_end_day: 30, domiciliacion_offset_days: null },

  // ---- Retenciones ----
  { code: "modelo_111", name: "Modelo 111 — Retenciones IRPF (nóminas y profesionales)", category: "Retenciones", periodicity: "trimestral",
    description: "Retenciones e ingresos a cuenta sobre rendimientos del trabajo y de actividades profesionales pagados.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    quarterly_q4_extended: false, domiciliacion_offset_days: 5 },
  { code: "modelo_190", name: "Modelo 190 — Resumen anual de retenciones (111)", category: "Retenciones", periodicity: "anual",
    description: "Resumen anual de las retenciones declaradas en el modelo 111. Informativo, sin cuota a domiciliar.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    deadline_start_month: 1, deadline_start_day: 1, deadline_end_month: 1, deadline_end_day: 31, domiciliacion_offset_days: null },
  { code: "modelo_115", name: "Modelo 115 — Retenciones por alquiler de local/oficina", category: "Retenciones", periodicity: "trimestral",
    description: "Retención e ingreso a cuenta sobre las rentas de alquiler de inmuebles urbanos afectos a la actividad.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    quarterly_q4_extended: false, domiciliacion_offset_days: 5 },
  { code: "modelo_180", name: "Modelo 180 — Resumen anual de retenciones de alquileres (115)", category: "Retenciones", periodicity: "anual",
    description: "Resumen anual de las retenciones declaradas en el modelo 115. Informativo, sin cuota a domiciliar.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    deadline_start_month: 1, deadline_start_day: 1, deadline_end_month: 1, deadline_end_day: 31, domiciliacion_offset_days: null },
  { code: "modelo_123", name: "Modelo 123 — Retenciones sobre capital mobiliario", category: "Retenciones", periodicity: "trimestral",
    description: "Retenciones e ingresos a cuenta sobre dividendos, intereses u otros rendimientos del capital mobiliario pagados.",
    fisica_residente: false, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: false,
    quarterly_q4_extended: false, domiciliacion_offset_days: 5 },
  { code: "modelo_193", name: "Modelo 193 — Resumen anual retenciones capital mobiliario (123)", category: "Retenciones", periodicity: "anual",
    description: "Resumen anual de las retenciones declaradas en el modelo 123. Informativo, sin cuota a domiciliar.",
    fisica_residente: false, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: false,
    deadline_start_month: 1, deadline_start_day: 1, deadline_end_month: 1, deadline_end_day: 31, domiciliacion_offset_days: null },
  { code: "modelo_216", name: "Modelo 216 — Retenciones practicadas a no residentes", category: "Retenciones", periodicity: "trimestral",
    description: "Ingreso de las retenciones practicadas sobre pagos realizados a no residentes sin establecimiento permanente.",
    fisica_residente: false, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    quarterly_q4_extended: false, domiciliacion_offset_days: 5 },
  { code: "modelo_296", name: "Modelo 296 — Resumen anual de retenciones a no residentes (216)", category: "Retenciones", periodicity: "anual",
    description: "Resumen anual de las retenciones declaradas en el modelo 216. Informativo, sin cuota a domiciliar.",
    fisica_residente: false, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    deadline_start_month: 1, deadline_start_day: 1, deadline_end_month: 1, deadline_end_day: 31, domiciliacion_offset_days: null },

  // ---- Impuesto sobre Sociedades ----
  { code: "modelo_200", name: "Modelo 200 — Impuesto sobre Sociedades", category: "IS", periodicity: "anual",
    description: "Declaración anual del Impuesto sobre Sociedades (ejercicio coincidente con año natural). Para no residentes, aplica cuando operan mediante establecimiento permanente en España.",
    fisica_residente: false, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    deadline_start_month: 7, deadline_start_day: 1, deadline_end_month: 7, deadline_end_day: 25, domiciliacion_offset_days: 5 },
  { code: "modelo_202", name: "Modelo 202 — Pago fraccionado del Impuesto sobre Sociedades", category: "IS", periodicity: "puntual",
    description: "Pagos a cuenta del Impuesto sobre Sociedades en los primeros 20 días de abril, octubre y diciembre. Calendario no automatizado (no encaja en trimestres estándar) — añade recordatorios manuales.",
    fisica_residente: false, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true },

  // ---- Informativos ----
  { code: "modelo_347", name: "Modelo 347 — Declaración de operaciones con terceros", category: "Informativo", periodicity: "anual",
    description: "Operaciones con un mismo tercero superiores a 3.005,06€ en el año natural. Informativo, sin cuota a domiciliar.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    deadline_start_month: 2, deadline_start_day: 1, deadline_end_month: 2, deadline_end_day: 28, domiciliacion_offset_days: null },
  { code: "modelo_349", name: "Modelo 349 — Operaciones intracomunitarias", category: "Informativo", periodicity: "trimestral",
    description: "Declaración recapitulativa de entregas, adquisiciones y prestaciones de servicios intracomunitarias. Informativo.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    quarterly_q4_extended: false, domiciliacion_offset_days: null },
  { code: "modelo_720", name: "Modelo 720 — Bienes y derechos en el extranjero", category: "Informativo", periodicity: "anual",
    description: "Cuentas, valores o inmuebles en el extranjero superiores a 50.000€ por bloque. Informativo, sin cuota a domiciliar.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: false,
    deadline_start_month: 1, deadline_start_day: 1, deadline_end_month: 3, deadline_end_day: 31, domiciliacion_offset_days: null },
  { code: "modelo_232", name: "Modelo 232 — Operaciones vinculadas y con paraísos fiscales", category: "Informativo", periodicity: "anual",
    description: "Información sobre operaciones con personas/entidades vinculadas y con paraísos fiscales (ejercicio coincidente con año natural). Informativo.",
    fisica_residente: false, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true,
    deadline_start_month: 11, deadline_start_day: 1, deadline_end_month: 11, deadline_end_day: 30, domiciliacion_offset_days: null },

  // ---- Formal / registral ----
  { code: "modelo_036", name: "Modelo 036 — Alta, modificación o baja censal", category: "Formal", periodicity: "puntual",
    description: "Declaración censal de inicio, modificación o cese de actividad ante la Agencia Tributaria.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: true },
  { code: "cuentas_anuales", name: "Depósito de cuentas anuales (Registro Mercantil)", category: "Formal", periodicity: "anual",
    description: "Depósito de las cuentas anuales en el Registro Mercantil (aprobación en los 6 meses tras el cierre del ejercicio; depósito en el mes siguiente). No es un modelo AEAT ni es domiciliable.",
    fisica_residente: false, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: false,
    deadline_start_month: 7, deadline_start_day: 1, deadline_end_month: 7, deadline_end_day: 30, domiciliacion_offset_days: null },
  { code: "iae", name: "IAE — Impuesto de Actividades Económicas", category: "Formal", periodicity: "anual",
    description: "Obligatorio solo para negocios con facturación superior a 1M€ (o tras los primeros 2 años de actividad). No es un modelo autoliquidable, se gestiona vía padrón municipal/AEAT.",
    fisica_residente: true, fisica_no_residente: false, juridica_residente: true, juridica_no_residente: false },
  { code: "ibi", name: "IBI — Impuesto sobre Bienes Inmuebles", category: "Local", periodicity: "anual",
    description: "Impuesto municipal anual sobre la titularidad de un inmueble en España. Lo gestiona el ayuntamiento, no la AEAT; el plazo varía según el municipio.",
    fisica_residente: true, fisica_no_residente: true, juridica_residente: true, juridica_no_residente: true },
  { code: "representante_fiscal", name: "Representante fiscal en España", category: "Formal", periodicity: "puntual",
    description: "Obligatorio en determinados supuestos para no residentes de fuera de la UE/EEE (titularidad de inmuebles, actividad económica).",
    fisica_residente: false, fisica_no_residente: true, juridica_residente: false, juridica_no_residente: true },
  { code: "modelo_650_651", name: "Modelo 650/651 — Impuesto de Sucesiones y Donaciones", category: "Formal", periodicity: "puntual",
    description: "Por herencias o donaciones de bienes situados en España. Plazo: 6 meses desde el fallecimiento (prorrogable) o 30 días desde la donación — no cubierto por el calendario automático.",
    fisica_residente: true, fisica_no_residente: true, juridica_residente: false, juridica_no_residente: false },

  // ---- No residentes: Modelo 210 (IRNR sin establecimiento permanente) ----
  { code: "modelo_210_alquiler", name: "Modelo 210 — Rendimientos de alquiler", category: "IRNR", periodicity: "trimestral",
    description: "IRNR trimestral sobre los ingresos por alquiler de inmuebles en España (clave 01). No domiciliable: pago mediante NRC.",
    fisica_residente: false, fisica_no_residente: true, juridica_residente: false, juridica_no_residente: true,
    quarterly_q4_extended: false, domiciliacion_offset_days: null },
  { code: "modelo_210_imputacion", name: "Modelo 210 — Imputación de rentas inmobiliarias", category: "IRNR", periodicity: "anual",
    description: "IRNR anual por la posesión de un inmueble en España no alquilado (uso propio o vacío), sobre el 1,1%–2% del valor catastral (clave 02). No domiciliable: pago mediante NRC.",
    fisica_residente: false, fisica_no_residente: true, juridica_residente: false, juridica_no_residente: true,
    deadline_start_month: 1, deadline_start_day: 1, deadline_end_month: 12, deadline_end_day: 31, domiciliacion_offset_days: null },
  { code: "modelo_210_venta", name: "Modelo 210 — Ganancia por venta de inmueble", category: "IRNR", periodicity: "puntual",
    description: "IRNR sobre la plusvalía obtenida en la venta de un inmueble en España (clave 28), tipo general 19%. Plazo: 4 meses desde la venta — no cubierto por el calendario automático.",
    fisica_residente: false, fisica_no_residente: true, juridica_residente: false, juridica_no_residente: true },
  { code: "modelo_210_otras_rentas", name: "Modelo 210 — Otras rentas de fuente española", category: "IRNR", periodicity: "puntual",
    description: "Dividendos, intereses, cánones u otras rentas de fuente española obtenidas sin establecimiento permanente.",
    fisica_residente: false, fisica_no_residente: true, juridica_residente: false, juridica_no_residente: true },
  { code: "modelo_211", name: "Modelo 211 — Retención del 3% en compra a no residente", category: "IRNR", periodicity: "puntual",
    description: "Retención que practica el comprador de un inmueble a un vendedor no residente, a cuenta del IRNR de este último. Plazo: 1 mes desde la venta.",
    fisica_residente: false, fisica_no_residente: true, juridica_residente: false, juridica_no_residente: true },
];
